matrix:
  include:
    - language: node_js
      os: linux
      dist: focal
      before_install:
       - nvm install 14.6.0
       - nvm use 14.6.0
      install:
      - npm install --global markdownlint-cli
      script:
      - markdownlint *.md
      - markdownlint doc/*.md
    - language: shell
      os: linux
      dist: focal
      install:
      - sudo apt-get install -y shellcheck -qq
      script:
      - sudo sh -e check.sh
