#!/bin/bash -eu

if [ -e /tmp/keep_awake_task_pid ]
then
  log "Stopping wake car background task."
  kill "$(cat /tmp/keep_awake_task_pid)" || true
  rm -f /tmp/keep_awake_task_pid
  log "Initiate TeslaFi sleep attempt."
  curl "https://www.teslafi.com/feed.php?token=TESLATFI_API_TOKEN&command=sleep"
fi
