#!/bin/bash -eu

# If Sentry Mode was previously disabled, restore it to that state

if [ -e /tmp/keep_awake_task_pid ]
then
  log "Stopping wake background task."
  kill "$(cat /tmp/keep_awake_task_pid)" || true
  rm -f /tmp/keep_awake_task_pid
  log "Start TeslaFi sleep attempt."
  curl "https://www.teslafi.com/feed.php?token=f2cc21945a086bb42c7d0749a7cb10d19216c98874a6da1523fc321bcb35adef&command=sleep"
fi

